-- 0007_simulated_flag.sql
-- Mark data generated by the simulator so it can be filtered and deleted
-- without touching real SDK data. DEFAULT false means all existing rows
-- automatically become "real" data with no manual backfill.

alter table gamepulse.players  add column if not exists is_simulated boolean not null default false;
alter table gamepulse.sessions add column if not exists is_simulated boolean not null default false;
alter table gamepulse.events   add column if not exists is_simulated boolean not null default false;
alter table gamepulse.crashes  add column if not exists is_simulated boolean not null default false;

-- Indexes for efficient filtering in analytics queries and fast deletion
create index if not exists players_sim_idx  on gamepulse.players  (project_id, is_simulated);
create index if not exists sessions_sim_idx on gamepulse.sessions (project_id, is_simulated);
create index if not exists events_sim_idx   on gamepulse.events   (project_id, is_simulated);
create index if not exists crashes_sim_idx  on gamepulse.crashes  (project_id, is_simulated);
