API_KEY_HEADER = "X-GamePulse-Key"
PROJECT_HEADER = "X-GamePulse-Project"
REQUEST_ID_HEADER = "X-Request-ID"

DEFAULT_BATCH_SIZE = 50
DEFAULT_FLUSH_INTERVAL_S = 2.0
MAX_BATCH_SIZE = 500
MAX_PAYLOAD_BYTES = 256 * 1024

DEFAULT_SESSION_TIMEOUT_S = 30 * 60
DEFAULT_HEARTBEAT_INTERVAL_S = 60
