from __future__ import annotations

from datetime import UTC, datetime, timedelta

import pandas as pd
import streamlit as st

# ── Date range ───────────────────────────────────────────────────────────────
# Preset label → number of lookback days. ``None`` means "ask for a custom range".
_RANGE_PRESETS: dict[str, int | None] = {
    "Last 24 hours": 1,
    "Last 7 days": 7,
    "Last 30 days": 30,
    "Last 90 days": 90,
    "Custom…": None,
}


def date_range(default: str = "Last 7 days", *, key: str = "date_range") -> int:
    """Sidebar date-range selector. Returns a lookback window in **days**.

    Backwards compatible with every `/v1/query/*` endpoint, which all take a
    `days` parameter. The custom option lets the user pick an explicit range.
    """
    labels = list(_RANGE_PRESETS)
    choice = st.sidebar.selectbox(
        "Date range", labels, index=labels.index(default), key=key
    )
    preset = _RANGE_PRESETS[choice]
    if preset is not None:
        return preset

    today = datetime.now(UTC).date()
    picked = st.sidebar.date_input(
        "Custom range",
        value=(today - timedelta(days=7), today),
        max_value=today,
        key=f"{key}_custom",
    )
    # date_input returns a single date until both ends are chosen.
    if isinstance(picked, tuple) and len(picked) == 2:
        start, end = picked
    else:
        start = picked if not isinstance(picked, tuple) else picked[0]
        end = today
    return max((end - start).days, 1)


def lookback_days(default: int = 7, max_days: int = 90, label: str = "Lookback (days)") -> int:
    """Legacy single-slider lookback. Prefer `date_range()` for new pages."""
    return st.sidebar.slider(label, 1, max_days, default)


def row_limit(default: int = 200, max_n: int = 2000, label: str = "Row limit") -> int:
    return st.sidebar.slider(label, 10, max_n, default)


def sim_data_filter() -> bool:
    """Sidebar checkbox; returns True when simulated data should be excluded."""
    return st.sidebar.checkbox(
        "Hide demo/simulated data",
        value=False,
        key="exclude_simulated",
        help="When checked, simulated data generated by the Simulation page is "
        "excluded from all charts and tables.",
    )


# ── Client-side dimension filters (for pages that receive row-level data) ─────
def dimension_filter(
    df: pd.DataFrame,
    column: str,
    label: str | None = None,
    *,
    key: str | None = None,
) -> pd.DataFrame:
    """Render a sidebar multiselect for a column's distinct values and filter.

    No-op (returns df unchanged) if the column is missing or empty. Safe to chain.
    """
    if df.empty or column not in df.columns:
        return df
    options = sorted({str(v) for v in df[column].dropna().unique()})
    if not options:
        return df
    picked = st.sidebar.multiselect(
        label or column.replace("_", " ").title(),
        options,
        default=[],
        key=key or f"filter_{column}",
    )
    if not picked:
        return df
    return df[df[column].astype(str).isin(picked)]


def search_box(
    df: pd.DataFrame, columns: list[str], *, label: str = "Search", key: str = "search"
) -> pd.DataFrame:
    """Free-text filter across the given columns (case-insensitive substring)."""
    term = st.sidebar.text_input(label, "", key=key).strip()
    if not term or df.empty:
        return df
    present = [c for c in columns if c in df.columns]
    if not present:
        return df
    mask = pd.Series(False, index=df.index)
    for c in present:
        mask = mask | df[c].astype(str).str.contains(term, case=False, na=False)
    return df[mask]
