from datetime import datetime

import pandas as pd
import streamlit as st
from lib.api_client import get
from lib.auth import require_project
from lib.ui import api_error, empty_state, page_header

require_project()
page_header("📡 Live Events", "Tail of the most recent telemetry events")

# ── Sidebar controls ──────────────────────────────────────────────────────────
# These live OUTSIDE the fragment so they never reset on auto-refresh.
# All use explicit keys so the fragment can read their current values from
# st.session_state without needing the widgets to re-render.
with st.sidebar:
    st.subheader("Filters")
    _categories = [
        "", "system", "progression", "economy",
        "gameplay", "social", "error", "custom",
    ]
    st.selectbox(
        "Category",
        _categories,
        index=0,
        key="le_category",
        format_func=lambda x: x or "All categories",
    )
    st.text_input(
        "Event type (e.g. progression.level_start)",
        "",
        key="le_event_type",
    )
    st.slider("Tail size", 50, 1000, 200, key="le_limit")
    st.checkbox(
        "Hide demo/simulated data",
        value=False,
        key="exclude_simulated",
        help="Exclude data generated by the Simulation page",
    )

    st.divider()
    st.subheader("🔄 Live refresh")
    st.checkbox("Auto-refresh", value=True, key="le_auto_refresh")
    st.select_slider(
        "Interval",
        options=[2, 3, 5, 10, 30],
        value=5,
        key="le_interval",
        format_func=lambda x: f"{x} s",
    )

# ── Fragment ──────────────────────────────────────────────────────────────────
# run_every is re-evaluated each time the parent script runs (i.e. on any
# sidebar interaction). Streamlit picks up the new value and adjusts the timer.
_run_every = (
    st.session_state.get("le_interval", 5)
    if st.session_state.get("le_auto_refresh", True)
    else None
)


@st.fragment(run_every=_run_every)
def live_pane() -> None:
    # Read sidebar state — persists across fragment-only re-runs.
    category: str | None = st.session_state.get("le_category") or None
    event_type: str = (st.session_state.get("le_event_type") or "").strip()
    limit: int = st.session_state.get("le_limit", 200)
    exclude_sim: bool = st.session_state.get("exclude_simulated", False)
    auto_refresh: bool = st.session_state.get("le_auto_refresh", True)
    interval: int = st.session_state.get("le_interval", 5)

    # Status bar + manual refresh button
    col_btn, col_status = st.columns([1, 5])
    with col_btn:
        st.button("🔄 Refresh now", key="le_manual_btn")
    with col_status:
        now_str = datetime.now().strftime("%H:%M:%S")
        if auto_refresh:
            refresh_note = f"auto-refreshing every {interval} s"
        else:
            refresh_note = "auto-refresh off — use the button or toggle above"
        st.caption(f"Last updated **{now_str}** · {refresh_note}")

    # Fetch
    rows: list = []
    try:
        rows = get(
            "/v1/query/events/recent",
            limit=limit,
            category=category,
            exclude_simulated=exclude_sim,
        )
    except Exception as exc:
        api_error(exc)
        return

    df = pd.DataFrame(rows)

    # Client-side type filter (substring match)
    if event_type and not df.empty and "type" in df.columns:
        df = df[df["type"].str.contains(event_type, case=False, na=False)]

    count_note = f"Showing {len(df)} event(s)"
    if event_type:
        count_note += f" — filtered by `{event_type}`"
    st.caption(count_note)

    if df.empty:
        empty_state("No matching events", "Adjust the filters or run the simulator")
        return

    # Format timestamps to HH:MM:SS for readability
    if "occurred_at" in df.columns:
        df["occurred_at"] = (
            pd.to_datetime(df["occurred_at"], errors="coerce")
            .dt.strftime("%H:%M:%S")
        )

    _icon = {
        "system": "⚙️",
        "progression": "🎯",
        "economy": "💰",
        "gameplay": "🕹️",
        "social": "🤝",
        "error": "💥",
        "custom": "🔧",
    }
    if "category" in df.columns:
        df.insert(0, " ", df["category"].map(_icon).fillna("❓"))
        col_order = [" ", "occurred_at", "type", "name", "player_id", "payload"]
        df = df[[c for c in col_order if c in df.columns]].rename(
            columns={"occurred_at": "time"}
        )

    st.dataframe(df, use_container_width=True, hide_index=True, height=520)


live_pane()
